package document

import (
	"bytes"
	"html/template"
	"strconv"
)

// Generator renders procurement summary documents.
type Generator interface {
	RenderProcurementSummary(summary ProcurementSummaryResponse) (string, error)
}

type htmlGenerator struct {
	template *template.Template
}

// NewHTMLGenerator creates a semantic printable HTML generator.
func NewHTMLGenerator() Generator {
	return &htmlGenerator{
		template: template.Must(template.New("procurement-summary").Funcs(template.FuncMap{
			"money": func(value float64) string {
				return formatFloat(value)
			},
		}).Parse(procurementSummaryTemplate)),
	}
}

// RenderProcurementSummary renders a printable procurement summary HTML document.
func (g *htmlGenerator) RenderProcurementSummary(summary ProcurementSummaryResponse) (string, error) {
	var buffer bytes.Buffer
	if err := g.template.Execute(&buffer, summary); err != nil {
		return "", err
	}
	return buffer.String(), nil
}

func formatFloat(value float64) string {
	return strconv.FormatFloat(value, 'f', 2, 64)
}

const procurementSummaryTemplate = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Procurement Summary {{ .DocumentNumber }}</title>
  <style>
    body { color: #1f2937; font-family: Arial, sans-serif; line-height: 1.5; margin: 40px; }
    header { border-bottom: 2px solid #111827; margin-bottom: 24px; padding-bottom: 16px; }
    h1 { font-size: 24px; margin: 0 0 8px; }
    h2 { border-bottom: 1px solid #d1d5db; font-size: 18px; margin-top: 28px; padding-bottom: 6px; }
    dl { display: grid; grid-template-columns: 220px 1fr; gap: 8px 16px; }
    dt { color: #4b5563; font-weight: 700; }
    dd { margin: 0; }
    table { border-collapse: collapse; margin-top: 12px; width: 100%; }
    th, td { border: 1px solid #d1d5db; padding: 8px; text-align: left; vertical-align: top; }
    th { background: #f3f4f6; }
    tfoot td { font-weight: 700; }
    .note { color: #4b5563; font-size: 12px; margin-top: 28px; }
    @media print { body { margin: 20mm; } }
  </style>
</head>
<body>
  <header>
    <h1>Procurement Summary</h1>
    <p>This document summarizes agreed business terms. It is not an invoice, payment receipt, or shipping document.</p>
  </header>

  <section>
    <h2>Document Information</h2>
    <dl>
      <dt>Document Number</dt><dd>{{ .DocumentNumber }}</dd>
      <dt>Generated Date</dt><dd>{{ .GeneratedDate.Format "2006-01-02 15:04 MST" }}</dd>
      <dt>Agreement ID</dt><dd>{{ .AgreementID }}</dd>
      <dt>Agreement Status</dt><dd>{{ .AgreementStatus }}</dd>
    </dl>
  </section>

  <section>
    <h2>Parties</h2>
    <dl>
      <dt>Producer Company</dt><dd>{{ .ProducerCompany }}</dd>
      <dt>Buyer Company</dt><dd>{{ .BuyerCompany }}</dd>
    </dl>
  </section>

  <section>
    <h2>Product List</h2>
    <table>
      <thead>
        <tr>
          <th>Product</th>
          <th>Quantity</th>
          <th>Unit</th>
          <th>Unit Price</th>
          <th>Currency</th>
          <th>Total</th>
          <th>Specifications</th>
          <th>Delivery Date</th>
        </tr>
      </thead>
      <tbody>
        {{ range .ProductList }}
        <tr>
          <td>{{ .ProductName }}</td>
          <td>{{ .Quantity }}</td>
          <td>{{ .Unit }}</td>
          <td>{{ money .UnitPrice }}</td>
          <td>{{ .Currency }}</td>
          <td>{{ money .TotalValue }}</td>
          <td>{{ .Specifications }}</td>
          <td>{{ .DeliveryDate.Format "2006-01-02" }}</td>
        </tr>
        {{ end }}
      </tbody>
      <tfoot>
        <tr>
          <td colspan="5">Total Value</td>
          <td colspan="3">{{ .Currency }} {{ money .TotalValue }}</td>
        </tr>
      </tfoot>
    </table>
  </section>

  <section>
    <h2>Terms</h2>
    <dl>
      <dt>Delivery Address</dt><dd>{{ .DeliveryAddress }}</dd>
      <dt>Payment Terms</dt><dd>{{ .PaymentTerms }}</dd>
      <dt>Additional Notes</dt><dd>{{ .AdditionalNotes }}</dd>
      <dt>Producer Confirmation</dt><dd>{{ if .ProducerConfirmationTimestamp }}{{ .ProducerConfirmationTimestamp.Format "2006-01-02 15:04 MST" }}{{ else }}-{{ end }}</dd>
      <dt>Buyer Confirmation</dt><dd>{{ if .BuyerConfirmationTimestamp }}{{ .BuyerConfirmationTimestamp.Format "2006-01-02 15:04 MST" }}{{ else }}-{{ end }}</dd>
    </dl>
  </section>

  <p class="note">Generated by FoodLink AI for pre-transaction procurement review.</p>
</body>
</html>`
